### PR TITLE
change recipe format to rattler-build

### PR DESCRIPTION
**Pull request by skontar-altair**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by skontar-altair** [comment]
@conda-forge-admin, please rerender

**Comment by skontar-altair** [comment]
@conda-forge-admin, please rerender

**Comment by skontar-altair** [comment]
@conda-forge-admin, please rerender

**Comment by skontar-altair** [comment]
@conda-forge/core can you help me why the build consistently fails with the new v1 recipe format proposed by the prefix.dev team? The reason in the logs seems to be that no recipe file is found. I have done everything that was written in the instructions, but for some odd reason conda-smithy only looks for `meta.yaml` file, not noticing the `recipe.yaml` file. I believe the `recipe.yaml` file is correct; I created it using the `conda-recipe-manager` tool, and validated it manually as well according to the relevant CEP. 
UPDATE: I also tried to build locally using `rattler-build` and the recipe in this PR, and it went off without a hitch.

**Comment by wolfv** [comment]
Did you already change the build tool in the conda-forge.yml file?

**Comment by skontar-altair** [comment]
the [docs on prefix.dev|https://prefix.dev/blog/rattler_build_on_conda_forge] did not mention I needed to, but I would appreciate your input:
```
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  error_overlinking: true
conda_forge_output_validation: true
```

**Comment by skontar-altair** [comment]
good point, just found the relevant docs on conda-forge docs page. thanks! I guess that will be the culprit.

**Comment by skontar-altair** [comment]
@conda-forge-admin, please rerender

**Pull request merged**
